name: Build and Release Packages

on:
  push:
    tags:
      - 'v*' # Срабатывает только при пуше тегов вида v0.1.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: actions/setup-cmake@v3  # Обновлено до v3
        with:
          cmake-version: '3.22.x'

      - name: Configure project
        run: |
          mkdir -p _build
          cd _build
          cmake ..
      - name: Build packages (DEB, RPM)
        run: |
          cd _build
          cpack -G DEB
          cpack -G RPM
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          path: |
            _build/*.deb
            _build/*.rpm

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: actions/setup-cmake@v3  # Обновлено до v3
        with:
          cmake-version: '3.22.x'

      - name: Configure project
        run: |
          mkdir -p _build
          cd _build
          cmake ..
      - name: Build package (DMG)
        run: |
          cd _build
          cpack -G DragNDrop
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-package
          path: _build/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset -y
      - name: Setup CMake
        uses: actions/setup-cmake@v3  # Обновлено до v3
        with:
          cmake-version: '3.22.x'

      - name: Configure project
        run: |
          mkdir -p _build
          cd _build
          cmake .. -G "Visual Studio 17 2022" -A x64
      - name: Build package (MSI)
        run: |
          cd _build
          cpack -G WIX
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: _build/*.msi

  upload-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux DEB package
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/linux-packages/*.deb
          tag_name: ${{ github.ref_name }}

      - name: Upload Linux RPM package
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/linux-packages/*.rpm
          tag_name: ${{ github.ref_name }}

      - name: Upload macOS DMG
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/macos-package/*.dmg
          tag_name: ${{ github.ref_name }}

      - name: Upload Windows MSI
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/windows-package/*.msi
          tag_name: ${{ github.ref_name }}

      - name: Archive source
        run: |
          VERSION=${{ github.ref_name }}
          tar -czf lab06-${VERSION}.tar.gz .
          zip -r lab06-${VERSION}.zip .
      
      - name: Upload Source Archives
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lab06-${VERSION}.tar.gz
            lab06-${VERSION}.zip
          tag_name: ${{ github.ref_name }}
