name: Build and Release Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновлено до v4

      - name: Install CMake and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure and build
        run: |
          mkdir -p _build
          cd _build
          cmake ..
          cpack -G DEB
          cpack -G RPM

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Обновлено до v4
        with:
          name: linux-packages
          path: _build/*.deb _build/*.rpm

  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          brew update
          brew install cmake

      - name: Configure and build
        run: |
          mkdir -p _build
          cd _build
          cmake ..
          cpack -G DragNDrop

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: _build/*.dmg

  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install wixtoolset -y

      - name: Configure and build
        run: |
          mkdir _build
          cd _build
          cmake .. -G "Visual Studio 17 2022" -A x64
          cpack -G WIX

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: _build/*.msi

  upload-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/linux-packages/*
            artifacts/macos-package/*
            artifacts/windows-package/*
