name: Build and Release Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install CMake and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure project
        run: |
          mkdir -p _build
          cd _build
          cmake ..
          
      - name: Build packages
        run: |
          cd _build
          cpack -G DEB
          cpack -G RPM
          
      - uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          path: _build/*.deb _build/*.rpm

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install CMake
        run: |
          brew install cmake

      - name: Configure project
        run: |
          mkdir -p _build
          cd _build
          cmake ..
          
      - name: Build package
        run: |
          cd _build
          cpack -G DragNDrop
          
      - uses: actions/upload-artifact@v3
        with:
          name: macos-package
          path: _build/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install wixtoolset -y

      - name: Configure project
        run: |
          mkdir _build
          cd _build
          cmake .. -G "Visual Studio 17 2022" -A x64
          
      - name: Build package
        run: |
          cd _build
          cpack -G WIX
          
      - uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: _build/*.msi

  upload-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/linux-packages/*
            artifacts/macos-package/*
            artifacts/windows-package/*
